<?php
return array(
    ["db_weiyi","t_invalid_num_confirm","id"],
    ["db_weiyi","t_deal_ppt_to_h5","id"],
    ["db_weiyi","t_cc_no_return_call","uid"],
    ["db_weiyi","t_seller_student_do_tag_log","id"],
    ["db_weiyi_admin","t_seller_student_system_release_log","id"],
    ["db_weiyi_admin","t_company_wx_approval_notify","d_id"],
    ["db_weiyi_admin","t_company_wx_approval_data","id"],
    ['db_weiyi','t_cc_day_top','id'],
    ['db_weiyi_admin','t_company_wx_approval','id'],
    ["db_tool","t_personality_poster","id"],
    ["db_tool","t_poster_share_log","poster_id"],
    ['db_weiyi','t_week_of_monthly_report','id'],
    ['db_weiyi','t_teacher_approve_refer_to_data','id'],
    ['db_weiyi','t_teacher_christmas','id'],
    ['db_weiyi','t_activity_usually','id'],
    ['db_weiyi','t_activity_christmas','id'],
    ['db_weiyi','t_teacher_full_part_trans_info','id'],
    ['db_weiyi','t_teacher_resource_dir','dir_id'],
    ['db_weiyi','t_teacher_resource','tea_res_id'],
    ["db_weiyi","t_channel_node_type_statistics","id"],
    ["db_weiyi","t_channel_funnel_archive_data","id"],
    ['db_weiyi','t_teacher_warn','id'],
    ["db_weiyi","t_resource_agree_info","agree_id"],
    ["db_weiyi","t_resource_file","file_id"],
    ["db_weiyi","t_resource_file_visit_info","visit_id"],
    ["db_weiyi","t_lore_info","lore_id"],
    ["db_weiyi","t_resource_lock_info","lock_id"],
    ["db_weiyi","t_resource","resource_id"],
    ['db_weiyi_admin','t_company_wx_tag_users','id'],
    ['db_weiyi_admin','t_company_wx_tag_department','id'],
    ["db_weiyi","t_tag_library","tag_id"],
    ['db_weiyi_admin','t_company_wx_tag','id'],
    ['db_weiyi','t_sum_activity_quota','id'],
    ['db_weiyi','t_activity_quota_detail','id'],
    ['db_weiyi','t_product_feedback_list','id'],
    ['db_weiyi_admin','t_company_wx_auth','id'],
    ['db_weiyi_admin','t_power_back','log_date', "groupid"],
    ['db_weiyi_admin','t_company_wx_role','id'],
    ['db_weiyi_admin',"t_company_wx_users","id"],
    ["db_weiyi_admin","t_company_wx_department","id"],
    ["db_weiyi","t_market_department_activity","lid"],
    ["db_weiyi","t_agent_daily_lottery","lid"],
    ["db_weiyi","t_agent_income_log","logid"],
    ["db_weiyi","t_agent_cash_money_freeze","id"],
    ["db_weiyi","t_agent_group_member_result","id"],
    ["db_weiyi","t_teacher_salary_list","id"],
    ["db_weiyi","t_teacher_simulate_salary_list","id"],
    ["db_weiyi_admin","t_web_page_info","web_page_id"],
    ["db_weiyi_admin","t_web_page_trace_log","id"],
    ["db_weiyi","t_luck_draw_yxyx_for_ruffian","id"],
    ["db_weiyi","t_ruffian_share","id"],
    ["db_weiyi","t_ruffian_activity","id"],
    ["db_weiyi","t_teacher_flow","teacherid"],
    ["db_weiyi","t_msg_log_for_wx","id"],
    ["db_weiyi","t_user_log","id"],
    ["db_weiyi","t_new_tea_entry","id"],
    ["db_weiyi_admin","t_agent_wx_msg_log","id"],
    ["db_weiyi_admin","t_interview_remind", "id"],
    ["db_weiyi","t_agent_group", "group_id"],
    ["db_weiyi","t_agent_group_members", "id"],
    ["db_weiyi","t_parent_send_mgs_log", "id"],
    ["db_weiyi","t_agent_money_ex", "id"],
    ["db_weiyi","t_wx_give_book", "id"],
    ["db_weiyi_admin","t_ssh_login_log", "id"],
    ["db_weiyi_admin","t_month_def_type","id"],
    ["db_weiyi","t_fulltime_teacher_data","id"],
    ["db_weiyi","t_order_activity_info", "orderid", "subid"],
    ["db_weiyi_admin","t_test_luki", "id"],
    ["db_weiyi","t_seller_tongji_for_month", "id"],
    ["db_weiyi_admin","t_user_group_change_log", "id"],
    ["db_weiyi","t_xmpp_server_config", "id"],
    ["db_weiyi_admin","t_main_major_group_name_month", "groupid"],
    ["db_weiyi_admin","t_tongji_log", "tongji_log_type", "logtime"],
    ["db_weiyi_admin","t_seller_level_goal", "seller_level"],
    ["db_weiyi_admin","t_seller_level_salary", "seller_level"],
    ["db_weiyi_admin","t_seller_level_month", "id"],
    ["db_weiyi_admin","t_seller_edit_log", "id"],
    ["db_weiyi_admin","t_mail_group_name", "groupid"],
    ["db_weiyi_admin","t_mail_group_user_list", "groupid", "adminid"  ],
    ["db_weiyi_admin","t_admin_majordomo_group_name", "groupid"],
    ["db_weiyi","t_wx_share", "id"],
    ["db_weiyi","t_teacher_day_luck_draw", "id"],
    ["db_weiyi","t_pdf_to_png_info", "id"],
    ["db_weiyi_admin","t_sys_error_info", "id"],
    ["db_weiyi_admin","t_config_date", "id"],
    ["db_weiyi_admin","t_admin_self_menu", "id"],
    ["db_weiyi_admin","t_flow_config", "flow_type"],
    ["db_weiyi","t_yxyx_wxnews_info", "id"],
    ["db_weiyi","t_yxyx_test_pic_info", "id"],
    ["db_weiyi","t_yxyx_test_pic_visit_info", "test_pic_id"],
    ["db_weiyi","t_yxyx_custom_type", "custom_type_id"],
    ["db_weiyi","t_yxyx_new_list", "id"],
    ["db_weiyi","t_grab_lesson_link_info", "grabid"],
    ["db_weiyi","t_grab_lesson_link_visit_info", "visitid"],
    ["db_weiyi","t_grab_lesson_link_visit_operation", "operationid"],
    ["db_weiyi","t_student_log", "id"],

    ["db_weiyi","t_teacher_switch_money_type_list", "id"],
    ["db_weiyi","t_teacher_reward_rule_list","rewrad_type"],
    ["db_weiyi","t_order_activity_config","id"],

    ["db_weiyi","t_parent_luck_draw_in_wx","id"],
    ["db_weiyi","t_lesson_time_modify","lessonid"],
    ["db_weiyi","t_user_login_log","id"],
    ["db_weiyi","t_student_score_info","id"],
    ["db_weiyi","t_student_cc_to_cr","id"],
    ["db_weiyi_admin","t_todo","todoid"],
    ["db_weiyi_admin","t_admin_work_start_time","id"],
    ["db_weiyi","t_complaint_info","complaint_id"],
    ["db_weiyi","t_complaint_assign_info","ass_id"],
    ["db_weiyi","t_complaint_deal_info","deal_id"],
    ["db_weiyi","t_agent","id"],
    ["db_weiyi","t_agent_order","orderid"],
    ["db_weiyi","t_agent_cash","id"],
    ["db_weiyi","t_cs_intended_user_info", "id"],
    ["db_weiyi","t_cs_complaint_user_info", "id"],
    ["db_weiyi","t_cs_proposal_info", "id"],
    ["db_weiyi","t_cr_week_month_info","id"],
    ["db_weiyi","t_requirement_info", "id"],
    ["db_weiyi","t_lesson_intro_video_info", "lessonid"],
    ["db_weiyi","t_child_order_info", "child_orderid"],
    ["db_weiyi","t_ass_stu_change_list", "id"],
    ["db_weiyi","t_rule_info", "rule_id"],
    ["db_weiyi","t_rule_detail_info", "detail_id"],
    ["db_weiyi","t_process_info", "process_id"],
    ["db_weiyi","jobs", "id"],
    ["db_weiyi_admin","t_log_event_type", "event_type_id"],
    ["db_weiyi_admin","t_log_event_log", "id"],


    ["db_weiyi_admin","t_user_report","id"],
    ["db_weiyi_admin","t_kaoqin_machine","machine_id"],
    ["db_weiyi_admin","t_kaoqin_machine_adminid","machine_id", "adminid"],
    ["db_weiyi_admin","t_seller_student_system_assign_log","id" ],
    ["db_weiyi_admin","t_seller_student_system_assign_count_log","logtime" ],


    ["db_weiyi","t_graduating_student_lesson_time_count","id"],
    ["db_weiyi_admin","t_refund_analysis","id"],
    ["db_weiyi_admin","t_order_refund_confirm_config","id"],
    ["db_weiyi_admin","t_admin_campus_list","campus_id"],
    ["db_weiyi_admin","t_order_info_finance","orderid"],


    ["db_weiyi_admin","t_admin_card_log","logtime","cardid"],
    ["db_weiyi_admin","t_id_opt_log","id"],
    ["db_weiyi_admin","t_seller_get_new_log","id"],
    ["db_weiyi_admin","t_seller_new_count","new_count_id"],
    ["db_weiyi_admin","t_seller_new_count_get_detail","id"],
    ["db_weiyi_admin","t_online_count_log","logtime"],
    ["db_weiyi_admin","t_online_count_xmpp_log","xmpp_id","logtime"],
    ["db_weiyi","t_seller_student_origin","userid","origin" ],
    ["db_weiyi","t_seller_student_new","userid" ],
    ["db_weiyi","t_test_lesson_subject","test_lesson_subject_id" ],
    ["db_weiyi","t_test_lesson_subject_require","require_id" ],
    ["db_weiyi","t_test_lesson_subject_sub_list","lessonid" ],
    ["db_weiyi","t_test_lesson_subject_require_review","id" ],
    ["db_weiyi","t_test_lesson_opt_log","roomid" ],
    ["db_weiyi","t_user_authority_group","groupid" ],
    ["db_weiyi","t_student_call_data","userid" ],


    ["db_weiyi","t_month_student_count","id"] ,
    ["db_weiyi","t_train_lesson_user","lessonid","userid"] ,
    ["db_weiyi","t_psychological_teacher_time_list","day","start"] ,
    ["db_weiyi","t_student_init_info","userid"] ,
    ["db_weiyi","t_gift_consign","exchangeid"] ,
    ["db_weiyi","t_gift_info","giftid"] ,
    ["db_weiyi","t_lesson_all_money_list","lessonid","orderid"] ,
    ["db_weiyi","t_lesson_info","lessonid"] ,
    ["db_weiyi","t_lesson_info_operate_log","id"] ,
    ["db_weiyi","t_homework_info","lessonid"] ,
    ["db_weiyi","t_course_order","courseid"] ,
    ["db_weiyi","t_order_course_list","courseid"] ,
    ["db_weiyi","t_small_class_user","courseid","userid"] ,
    ["db_weiyi","t_teacher_info","teacherid"] ,
    ["db_weiyi","t_teacher_record_list","id"],
    ["db_weiyi","t_teacher_feedback_list","teacherid"] ,
    ["db_weiyi","t_teacher_lecture_info","id"] ,
    ["db_weiyi","t_teacher_apply","id"] ,
    ["db_weiyi","t_revisit_info","userid","revisit_time" ] ,
    ["db_weiyi","t_revisit_assess_info","id" ] ,
    ["db_weiyi","t_revisit_call_count","count_id" ] ,
    ["db_weiyi","t_revisit_warning_overtime_info","overtime_id" ] ,
    ["db_weiyi","t_parent_info","parentid"] ,
    ["db_weiyi","t_error_info","id"] ,
    ["db_weiyi","t_quiz_info","quizid"] ,
    ["db_weiyi","t_assistant_info","assistantid"] ,
    ["db_weiyi","t_festival_info","id"] ,
    ["db_weiyi","t_opt_table_log","id"] ,
    ["db_weiyi","t_good_video_send_list","id"] ,
    ["db_weiyi","t_teacher_lecture_appointment_info","id"] ,
    ["db_weiyi","t_parent_child","parentid","userid"] ,
    ["db_weiyi","t_teacher_month_money","logtime","teacherid"] ,
    ["db_weiyi","t_month_ass_student_info","adminid","month","kpi_type"] ,
    ["db_weiyi","t_jw_teacher_month_plan_lesson_info","adminid","month"] ,
    ["db_weiyi","t_month_ass_warning_student_info","id"] ,
    ["db_weiyi","t_ass_warning_renw_flag_modefiy_list","id"] ,
    ["db_weiyi","t_teacher_phone_click_info","adminid","click_time"] ,
    ["db_weiyi","t_ass_weekly_info","id"] ,
    ["db_weiyi","t_teacher_money_type","teacher_money_type"] ,
    ["db_weiyi","t_teacher_label","id"] ,
    ["db_weiyi","t_field_modified_list","id"] ,
    ["db_weiyi","t_fulltime_teacher_attendance_list","id"] ,
    ["db_weiyi","t_test_lesson_require_teacher_list","id"] ,
    ["db_weiyi","t_student_type_change_list","id"] ,
    ["db_weiyi","t_orderid_orderno_list","order_no"] ,
    ["db_weiyi","t_tongji_date","__null_"] ,

    ["db_weiyi","t_taobao_item","open_iid"] ,
    ["db_weiyi","t_taobao_type_list","cid"] ,

    ["db_weiyi","t_audio_record_server","ip"] ,
    ["db_weiyi","t_baidu_msg","messageid"] ,
    ["db_weiyi","t_baidu_push_msg","messageid"] ,
    ["db_weiyi","t_mypraise","userid"] ,

    ["db_weiyi","t_teacher_money_list","id"] ,
    ["db_weiyi","t_teacher_freetime_for_week","teacherid"] ,
    ["db_weiyi","t_teacher_closest","uid"] ,
    ["db_weiyi","t_teacher_closest_grade","teacherid"] ,
    ["db_weiyi","t_teacher_closest_subject","teacherid"] ,
    ["db_weiyi","t_appointment_info","packageid"] ,
    ["db_weiyi","t_order_info","orderid"] ,
    ["db_weiyi","t_order_refund","orderid", "apply_time"] ,
    ["db_weiyi","t_order_lesson_list","orderid","lessonid"] ,
    ["db_weiyi","t_open_lesson_user","lessonid","userid"] ,
    ["db_weiyi","t_order_course_info","id"] ,
    ["db_weiyi","t_small_lesson_info","lessonid","userid"] ,
    ["db_weiyi","t_student_info","userid"] ,
    ["db_weiyi","t_book_info","id"] ,
    ["db_weiyi","t_book_revisit","phone","revisit_time"] ,
    ["db_weiyi","t_book_info","id"] ,
    ["db_weiyi","t_user_lesson_account","lesson_account_id"] ,
    ["db_weiyi","t_user_lesson_account_log","id"] ,
    ["db_weiyi","t_user_lesson_account_lesson","lesson_account_id", "lessonid"] ,
    ["db_weiyi","t_user_origin_info","phone"] ,
    ["db_weiyi","t_teacher_freetime_for_week","teacherid"] ,
    ["db_weiyi","t_lesson_opt_log", "__id"],
    ["db_weiyi","t_pic_manage_info", "id"],
    ["db_weiyi","t_seller_student_info", "phone"],
    ["db_weiyi","t_seller_student_info_sub", "id"],
    ["db_weiyi","t_test_lesson_log_list", "id"],
    ["db_weiyi","t_teacher_complaints_info", "id"],
    ["db_weiyi","t_seller_info", "sellerid"],
    ["db_weiyi","t_test_lesson_order_info_old", "teacherid","userid"],
    ["db_weiyi","t_lecture_revisit_info", "phone","revisit_time"],
    ["db_weiyi","t_test_subject_free_list", "userid","adminid"],
    ["db_weiyi","t_send_wx_template_record_list", "template_id","send_time"],
    ["db_weiyi","t_research_teacher_kpi_info", "kid","month"],
    ["db_weiyi","t_teacher_advance_list", "start_time","teacherid"],
    ["db_weiyi","t_teaching_core_data", "time","type"],
    ["db_weiyi","t_phone_info","id"],
    ["db_weiyi","t_resource_file_evalutation","id"],
    ["db_weiyi","t_resource_file_error_info","id"],
    ["db_weiyi","t_subject_grade_config", "adminid","type"],

    ["db_weiyi","t_origin_key", "value"],
    ["db_weiyi","t_wx_openid_bind","openid","role"] ,
    ["db_weiyi","t_test_lesson_assign_teacher","id"] ,
    ["db_weiyi","t_week_regular_course","teacherid","start_time"] ,
    ["db_weiyi","t_winter_week_regular_course","teacherid","start_time"] ,
    ["db_weiyi","t_summer_week_regular_course","teacherid","start_time"] ,
    ["db_weiyi","t_teacher_assess","teacherid","assess_time"] ,
    ["db_weiyi","t_teacher_meeting_info","id"] ,
    ["db_weiyi","t_teacher_meeting_join_info","teacherid","create_time"] ,
    ["db_weiyi","t_teacher_cancel_lesson_list","teacherid","cancel_time"] ,
    ["db_weiyi","t_research_teacher_rerward_list","courseid"] ,
    ["db_weiyi","t_change_teacher_list","id"] ,
    ["db_weiyi","t_seller_and_ass_record_list","id"] ,
    ["db_weiyi","t_teacher_leave_info","id"] ,
    ["db_weiyi","t_teacher_train_info","id"],
    ["db_weiyi","t_fulltime_teacher_assessment_list","id"] ,
    ["db_weiyi","t_fulltime_teacher_positive_require_list","id"] ,
    ["db_weiyi","t_location_subject_grade_textbook_info","id"] ,
    ["db_weiyi","t_student_subject_list","userid","subject"] ,
    ["db_weiyi","t_period_repay_list","orderid","period"] ,
    ["db_weiyi","t_version_control","id"] ,
    ["db_weiyi","t_sub_grade_book_tag","id"] ,
    ["db_weiyi","t_teacher_spring","id"],

    ["db_weiyi_admin","t_upload_info","postid"] ,
    ["db_weiyi_admin","t_upload_student_info","postid","phone"] ,

    ["db_weiyi_admin","t_flow","flowid"] ,
    ["db_weiyi_admin","t_flow_node","nodeid"] ,
    ["db_weiyi_admin","t_jiaqi_year_count","adminid", "year"] ,
    ["db_weiyi_admin","t_qingjia","id"],

    ["db_weiyi_admin","t_admin_card_date_log","logtime","cardid"] ,
    ["db_weiyi_admin","t_admin_group","groupid","adminid"] ,
    ["db_weiyi_admin","t_admin_group_name","groupid"] ,
    ["db_weiyi_admin","t_admin_group_user","groupid","adminid"] ,
    ["db_weiyi_admin","t_login_log","id"] ,
    ["db_weiyi_admin","t_manager_info","uid"] ,
    ["db_weiyi_admin","t_authority_group","groupid"] ,
    ["db_weiyi_admin","t_admin_users","id"] ,
    ["db_weiyi_admin","t_adid_to_adminid","adid","adminid"] ,
    ["db_weiyi_admin","t_tongji","id"] ,
    ["db_weiyi_admin","t_wx_user_info","openid"] ,
    ["db_weiyi_admin","t_wx_key_value","id"] ,
    ["db_weiyi_admin","t_tq_call_info","id"] ,
    ["db_weiyi_admin","t_apply_reg","phone"] ,
    ["db_weiyi_admin","t_tongji_seller_top_info","adminid","logtime","tongji_type"] ,
    ["db_weiyi_admin","t_admin_main_group_name","groupid"] ,
    ["db_weiyi_admin","t_seller_month_money_target","adminid","month"] ,
    ["db_weiyi_admin","t_assistant_month_target","adminid","month"] ,
    ["db_weiyi_admin","t_ass_group_target","month"] ,
    ["db_weiyi_admin","t_admin_group_month_time","groupid","month"] ,
    ["db_weiyi_admin","t_user_video_info","userid","lessonid","time"] ,
    ["db_weiyi_admin","t_group_name_month","groupid","month"] ,
    ["db_weiyi_admin","t_group_user_month","groupid","adminid","month"] ,
    ["db_weiyi_admin","t_main_group_name_month","groupid","month"] ,
    ["db_weiyi_admin","t_admin_channel_list","channel_id"] ,
    ["db_weiyi_admin","t_admin_channel_user","id"] ,
    ["db_weiyi_admin","t_admin_channel_group","ref_type"] ,
    ["db_weiyi_admin","t_admin_corporate_income_list","month"] ,
    ["db_weiyi_admin","t_admin_refund_order_list","id"] ,
    ["db_weiyi_admin","t_admin_student_month_info","month"] ,
    ["db_weiyi_admin","t_order_student_month_list","month","origin"] ,
    ["db_weiyi_admin","t_url_desc_power","id"] ,
    ["db_weiyi_admin","t_url_input_define","id"] ,
    ["db_weiyi_admin","t_user_power_group","id"] ,

    ["db_account","t_phone_to_user","phone"] ,
    ["db_account","t_user_info","userid"] ,

    ["db_tool","t_news_info","id"] ,
    ["db_tool","t_news_tags_info","id"] ,
    ["db_tool","t_news_headlines","id"] ,
    ["db_tool","t_news_activity_info","id"] ,
    ["db_tool","t_news_ad_info","id"] ,
    ["db_tool","t_paper_info","paperid"] ,
    ["db_tool","t_school_info","id"] ,
    ["db_tool","t_scores_info","id"] ,
    ["db_tool","t_scores_min","id"] ,
    ["db_message","t_sms_msg","recordid"] ,
    ["db_message","t_weixin_msg","recordid"],

    // ["db_ejabberd","users","username"] ,

    ["db_question_new","t_question","question_id"] ,
    ["db_question_new","t_knowledge_point","knowledge_id"] ,
    ["db_question_new","t_answer","step_id"] ,
    ["db_question_new","t_answer_type","id"],
    ["db_question_new","t_question_knowledge","id"],
    ["db_question_new","t_knowledge_level","id"],
    ["db_question_new","t_textbook","textbook_id"],
    ["db_question_new","t_textbook_knowledge","id"],
    ["db_question_new","t_question_type","id"],
    ["db_question_new","t_student_answer","id"],
    ["db_question_new","t_question_option","id"],

);
