version: "2"
services:
  web:
    image: nginx:1.12.1-alpine
    ports:
      - "8080:80"
    volumes:
      - ../:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - code-network
  mysql:
    image: mysql:5.6
    volumes:
      - ./dbdata:/var/lib/mysql
    ports:
      - "4306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: ta0mee 
      MYSQL_ROOT_PASSWORD: ta0mee 
    networks:
      - code-network
  php:
    build: ./php-fpm/
    volumes:
      - ../:/code
    networks:
      - code-network

  redis:
    image: redis:4.0
    ports:
      - "7379:6379"
    networks:
      - code-network

networks:
  code-network:
    driver: bridge
